{
  "name": "mbpp_287_square_Sum",
  "language": "php",
  "prompt": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n",
  "doctests": "keep",
  "original": "/home/arjun/repos/MultiPL-E/datasets/../datasets/mbpp-typed/mbpp_287_square_Sum.py",
  "prompt_terminology": "verbatim",
  "tests": "function candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
  "stop_tokens": [
    "\nfunction",
    "\n?>",
    "\n//",
    "\n#"
  ],
  "results": [
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n  $sum = 0;\n  for($i = 1; $i <= $n; $i++) {\n    $sum += $i * $i;\n  }\n  return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbq7dsw6h.php:17\nStack trace:\n#0 /tmp/tmpbq7dsw6h.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpbq7dsw6h.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjncsjihv.php:16\nStack trace:\n#0 /tmp/tmpjncsjihv.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpjncsjihv.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyfvz3q8q.php:16\nStack trace:\n#0 /tmp/tmpyfvz3q8q.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyfvz3q8q.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\necho \"\\n\";\necho square_Sum(5);\necho \"\\n\";\necho square_Sum(6);\necho \"\\n\";\necho square_Sum(7);\necho \"\\n\";\necho square_Sum(8);\necho \"\\n\";\necho square_Sum(9);\necho \"\\n\";\necho square_Sum(10);\necho \"\\n\";\necho square_Sum(11);\necho \"\\n\";\necho square_Sum(12);\necho \"\\n\";\necho square_Sum(13);\necho \"\\n\";\necho square_Sum(14);\necho \"\\n\";\necho square_Sum(15);\necho \"\\n\";\necho square_Sum(16);\necho \"\\n\";\necho square_Sum(17);\necho \"\\n\";\necho square_Sum(18);\necho \"\\n\";\necho square_Sum(19);\necho \"\\n\";\necho square_Sum(20);\necho \"\\n\";\necho square_Sum(21);\necho \"\\n\";\necho square_Sum(22);\necho \"\\n\";\necho square_Sum(23);\necho \"\\n\";\necho square_Sum(24);\necho \"\\n\";\necho square_Sum(25);\necho \"\\n\";\necho square_Sum(26);\necho \"\\n\";\necho square_Sum(27);\necho \"\\n\";\necho square_Sum(28);\necho \"\\n\";\necho square_Sum(29);\necho \"\\n\";\necho square_Sum(30);\necho \"\\n\";\necho square_Sum(31);\necho \"\\n\";\necho square_Sum(32);\necho \"\\n\";\necho square_Sum(33);\necho \"\\n\";\necho square_Sum(34);\necho \"\\n\";\necho square_Sum(35);\necho \"\\n\";\necho square_Sum(36);\necho \"\\n\";\necho square_Sum(37);\necho \"\\n\";\necho square_Sum(38);\necho \"\\n\";\necho square_Sum(39);\n\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\n55\n91\n140\n204\n285\n385\n506\n650\n819\n1015\n1240\n1496\n1785\n2109\n2470\n2870\n3311\n3795\n4324\n4900\n5525\n6201\n6930\n7714\n8555\n9455\n10416\n11440\n12529\n13685\n14910\n16206\n17575\n19019\n20540\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps5dd600w.php:88\nStack trace:\n#0 /tmp/tmps5dd600w.php(93): test()\n#1 {main}\n  thrown in /tmp/tmps5dd600w.php on line 88\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp30htqjq9.php:17\nStack trace:\n#0 /tmp/tmp30htqjq9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp30htqjq9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpf2mb64sl.php:17\nStack trace:\n#0 /tmp/tmpf2mb64sl.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpf2mb64sl.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpw2i_fiku.php:17\nStack trace:\n#0 /tmp/tmpw2i_fiku.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpw2i_fiku.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 2; $i <= $n * 2; $i += 2) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "56",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps_dkzcyp.php:17\nStack trace:\n#0 /tmp/tmps_dkzcyp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmps_dkzcyp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum += $i*$i;\n    }\n    return $sum;\n}\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpf0r7u0de.php:16\nStack trace:\n#0 /tmp/tmpf0r7u0de.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpf0r7u0de.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++){\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp4zcokih_.php:17\nStack trace:\n#0 /tmp/tmp4zcokih_.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp4zcokih_.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp7tjhhur7.php:19\nStack trace:\n#0 /tmp/tmp7tjhhur7.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp7tjhhur7.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbzqg79ml.php:17\nStack trace:\n#0 /tmp/tmpbzqg79ml.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpbzqg79ml.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp30htqjq9.php:17\nStack trace:\n#0 /tmp/tmp30htqjq9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp30htqjq9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqvres217.php:17\nStack trace:\n#0 /tmp/tmpqvres217.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpqvres217.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\n\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpog9hqx97.php:18\nStack trace:\n#0 /tmp/tmpog9hqx97.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpog9hqx97.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp89ikp9qp.php:17\nStack trace:\n#0 /tmp/tmp89ikp9qp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp89ikp9qp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n  $sum = 0;\n  for ($i = 1; $i <= $n; $i++) {\n    $sum += pow($i, 2);\n  }\n  return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpg135gon6.php:17\nStack trace:\n#0 /tmp/tmpg135gon6.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpg135gon6.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1;$i<=$n;$i++) {\n        $sum += pow(2*$i,2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "220",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\n\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqtgkeu80.php:18\nStack trace:\n#0 /tmp/tmpqtgkeu80.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpqtgkeu80.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6qavg_l9.php:17\nStack trace:\n#0 /tmp/tmp6qavg_l9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6qavg_l9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmprec3bouf.php:17\nStack trace:\n#0 /tmp/tmprec3bouf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmprec3bouf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "385\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjj7bv756.php:17\nStack trace:\n#0 /tmp/tmpjj7bv756.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpjj7bv756.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpf2mb64sl.php:17\nStack trace:\n#0 /tmp/tmpf2mb64sl.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpf2mb64sl.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp89ikp9qp.php:17\nStack trace:\n#0 /tmp/tmp89ikp9qp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp89ikp9qp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6japyxi1.php:17\nStack trace:\n#0 /tmp/tmp6japyxi1.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6japyxi1.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp30htqjq9.php:17\nStack trace:\n#0 /tmp/tmp30htqjq9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp30htqjq9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmprec3bouf.php:17\nStack trace:\n#0 /tmp/tmprec3bouf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmprec3bouf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyl_l6gqf.php:17\nStack trace:\n#0 /tmp/tmpyl_l6gqf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpyl_l6gqf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\n$n = 4;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpzomwm16q.php:18\nStack trace:\n#0 /tmp/tmpzomwm16q.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpzomwm16q.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbzqg79ml.php:17\nStack trace:\n#0 /tmp/tmpbzqg79ml.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpbzqg79ml.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpw2i_fiku.php:17\nStack trace:\n#0 /tmp/tmpw2i_fiku.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpw2i_fiku.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjncsjihv.php:16\nStack trace:\n#0 /tmp/tmpjncsjihv.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpjncsjihv.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmprec3bouf.php:17\nStack trace:\n#0 /tmp/tmprec3bouf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmprec3bouf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpf2mb64sl.php:17\nStack trace:\n#0 /tmp/tmpf2mb64sl.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpf2mb64sl.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "385\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpytabii7a.php:17\nStack trace:\n#0 /tmp/tmpytabii7a.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpytabii7a.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps_jg8tw9.php:16\nStack trace:\n#0 /tmp/tmps_jg8tw9.php(21): test()\n#1 {main}\n  thrown in /tmp/tmps_jg8tw9.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp89ikp9qp.php:17\nStack trace:\n#0 /tmp/tmp89ikp9qp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp89ikp9qp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\n\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqtgkeu80.php:18\nStack trace:\n#0 /tmp/tmpqtgkeu80.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpqtgkeu80.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpfblsctl1.php:16\nStack trace:\n#0 /tmp/tmpfblsctl1.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpfblsctl1.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\n$n = 5;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpylao0gea.php:18\nStack trace:\n#0 /tmp/tmpylao0gea.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpylao0gea.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 2; $i <= $n * 2; $i += 2) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp89ikp9qp.php:17\nStack trace:\n#0 /tmp/tmp89ikp9qp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp89ikp9qp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxp9k24ca.php:17\nStack trace:\n#0 /tmp/tmpxp9k24ca.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxp9k24ca.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n  $sum = 0;\n  for ($i = 1; $i <= $n; $i++) {\n    if ($i % 2 == 0) {\n      $sum += $i * $i;\n    }\n  }\n  return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8ndgyz8x.php:18\nStack trace:\n#0 /tmp/tmp8ndgyz8x.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp8ndgyz8x.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += ($i * $i);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp9k8nk48o.php:17\nStack trace:\n#0 /tmp/tmp9k8nk48o.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp9k8nk48o.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += ($i * $i);\n    }\n    return $sum;\n}\n\n$n = 3;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpfou0ndhy.php:18\nStack trace:\n#0 /tmp/tmpfou0ndhy.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpfou0ndhy.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp30htqjq9.php:17\nStack trace:\n#0 /tmp/tmp30htqjq9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp30htqjq9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpof2ak8v0.php:17\nStack trace:\n#0 /tmp/tmpof2ak8v0.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpof2ak8v0.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbzqg79ml.php:17\nStack trace:\n#0 /tmp/tmpbzqg79ml.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpbzqg79ml.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp30htqjq9.php:17\nStack trace:\n#0 /tmp/tmp30htqjq9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp30htqjq9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum += pow($i*2, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "120",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i=0; $i < $n; $i++) { \n        $sum += pow(2*$i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxx4gldpn.php:17\nStack trace:\n#0 /tmp/tmpxx4gldpn.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxx4gldpn.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyfvz3q8q.php:16\nStack trace:\n#0 /tmp/tmpyfvz3q8q.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyfvz3q8q.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum = $sum + ($i*$i);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpy7zdyyhx.php:17\nStack trace:\n#0 /tmp/tmpy7zdyyhx.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpy7zdyyhx.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6b9b30cy.php:18\nStack trace:\n#0 /tmp/tmp6b9b30cy.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp6b9b30cy.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        if($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpf_ty9vw5.php:19\nStack trace:\n#0 /tmp/tmpf_ty9vw5.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpf_ty9vw5.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n  $sum = 0;\n  for($i = 1; $i <= $n; $i++) {\n    $sum += pow($i, 2);\n  }\n  return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpestlzz5g.php:17\nStack trace:\n#0 /tmp/tmpestlzz5g.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpestlzz5g.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbzqg79ml.php:17\nStack trace:\n#0 /tmp/tmpbzqg79ml.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpbzqg79ml.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpnfvrmdvd.php:16\nStack trace:\n#0 /tmp/tmpnfvrmdvd.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpnfvrmdvd.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptz_g39n_.php:19\nStack trace:\n#0 /tmp/tmptz_g39n_.php(24): test()\n#1 {main}\n  thrown in /tmp/tmptz_g39n_.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp89ikp9qp.php:17\nStack trace:\n#0 /tmp/tmp89ikp9qp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp89ikp9qp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpl3m19qye.php:16\nStack trace:\n#0 /tmp/tmpl3m19qye.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpl3m19qye.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpmk34g_6t.php:17\nStack trace:\n#0 /tmp/tmpmk34g_6t.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpmk34g_6t.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp30htqjq9.php:17\nStack trace:\n#0 /tmp/tmp30htqjq9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp30htqjq9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps_jg8tw9.php:16\nStack trace:\n#0 /tmp/tmps_jg8tw9.php(21): test()\n#1 {main}\n  thrown in /tmp/tmps_jg8tw9.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6qavg_l9.php:17\nStack trace:\n#0 /tmp/tmp6qavg_l9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6qavg_l9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpof2ak8v0.php:17\nStack trace:\n#0 /tmp/tmpof2ak8v0.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpof2ak8v0.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        if($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpf_ty9vw5.php:19\nStack trace:\n#0 /tmp/tmpf_ty9vw5.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpf_ty9vw5.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n\t$sum = 0;\n\tfor ($i=1; $i <= $n; $i++) { \n\t\t$sum = $sum + ($i * $i);\n\t}\n\treturn $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpmf3oaizx.php:16\nStack trace:\n#0 /tmp/tmpmf3oaizx.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpmf3oaizx.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpof2ak8v0.php:17\nStack trace:\n#0 /tmp/tmpof2ak8v0.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpof2ak8v0.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp7gc54w7_.php:17\nStack trace:\n#0 /tmp/tmp7gc54w7_.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp7gc54w7_.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpf2mb64sl.php:17\nStack trace:\n#0 /tmp/tmpf2mb64sl.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpf2mb64sl.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpd1505vu_.php:16\nStack trace:\n#0 /tmp/tmpd1505vu_.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpd1505vu_.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i * 2, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "56",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6qavg_l9.php:17\nStack trace:\n#0 /tmp/tmp6qavg_l9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6qavg_l9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpnkbd2_rw.php:17\nStack trace:\n#0 /tmp/tmpnkbd2_rw.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpnkbd2_rw.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow(2 * $i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "120",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyfvz3q8q.php:16\nStack trace:\n#0 /tmp/tmpyfvz3q8q.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyfvz3q8q.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow(2 * $i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "220",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjncsjihv.php:16\nStack trace:\n#0 /tmp/tmpjncsjihv.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpjncsjihv.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp30htqjq9.php:17\nStack trace:\n#0 /tmp/tmp30htqjq9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp30htqjq9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpnkbd2_rw.php:17\nStack trace:\n#0 /tmp/tmpnkbd2_rw.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpnkbd2_rw.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1;$i<=$n;$i++) {\n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp42jdtv06.php:17\nStack trace:\n#0 /tmp/tmp42jdtv06.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp42jdtv06.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjncsjihv.php:16\nStack trace:\n#0 /tmp/tmpjncsjihv.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpjncsjihv.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8uqa3im9.php:17\nStack trace:\n#0 /tmp/tmp8uqa3im9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp8uqa3im9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6qavg_l9.php:17\nStack trace:\n#0 /tmp/tmp6qavg_l9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6qavg_l9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp7tjhhur7.php:19\nStack trace:\n#0 /tmp/tmp7tjhhur7.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp7tjhhur7.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpn8rv9ak9.php:17\nStack trace:\n#0 /tmp/tmpn8rv9ak9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpn8rv9ak9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8u2remfe.php:16\nStack trace:\n#0 /tmp/tmp8u2remfe.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp8u2remfe.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6japyxi1.php:17\nStack trace:\n#0 /tmp/tmp6japyxi1.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6japyxi1.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6japyxi1.php:17\nStack trace:\n#0 /tmp/tmp6japyxi1.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6japyxi1.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        if($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp20afy6yb.php:19\nStack trace:\n#0 /tmp/tmp20afy6yb.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp20afy6yb.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1;$i<=$n;$i++){\n        $sum = $sum + ($i*$i);\n    }\n    return $sum;\n}\n$n = 4;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp0m6me1vk.php:17\nStack trace:\n#0 /tmp/tmp0m6me1vk.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp0m6me1vk.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp30htqjq9.php:17\nStack trace:\n#0 /tmp/tmp30htqjq9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp30htqjq9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i * 2, 2);\n    }\n    return $sum;\n}\n\n$n = 5;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "220",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++){\n        $sum += pow($i*2, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(10);\n\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "1540",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        if($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpggc9nssh.php:19\nStack trace:\n#0 /tmp/tmpggc9nssh.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpggc9nssh.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp89ikp9qp.php:17\nStack trace:\n#0 /tmp/tmp89ikp9qp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp89ikp9qp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpw2i_fiku.php:17\nStack trace:\n#0 /tmp/tmpw2i_fiku.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpw2i_fiku.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += pow($i, 2);\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpp2snxbe9.php:19\nStack trace:\n#0 /tmp/tmpp2snxbe9.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpp2snxbe9.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps_jg8tw9.php:16\nStack trace:\n#0 /tmp/tmps_jg8tw9.php(21): test()\n#1 {main}\n  thrown in /tmp/tmps_jg8tw9.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i=1; $i <= $n; $i++) { \n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpr02ynfz1.php:17\nStack trace:\n#0 /tmp/tmpr02ynfz1.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpr02ynfz1.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i * 2, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "56",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum = $sum + pow(2*$i, 2);\n    }\n    return $sum;\n}\n\n$n = 5;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "220",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmprec3bouf.php:17\nStack trace:\n#0 /tmp/tmprec3bouf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmprec3bouf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i=1; $i <= $n; $i++) { \n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpr7z7tpdb.php:17\nStack trace:\n#0 /tmp/tmpr7z7tpdb.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpr7z7tpdb.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum += pow(2 * $i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "120",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\n\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpau4x7bm4.php:18\nStack trace:\n#0 /tmp/tmpau4x7bm4.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpau4x7bm4.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp89ikp9qp.php:17\nStack trace:\n#0 /tmp/tmp89ikp9qp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp89ikp9qp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbzqg79ml.php:17\nStack trace:\n#0 /tmp/tmpbzqg79ml.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpbzqg79ml.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i * 2, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "220",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow(2 * $i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "56",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6qavg_l9.php:17\nStack trace:\n#0 /tmp/tmp6qavg_l9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6qavg_l9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp30htqjq9.php:17\nStack trace:\n#0 /tmp/tmp30htqjq9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp30htqjq9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpof2ak8v0.php:17\nStack trace:\n#0 /tmp/tmpof2ak8v0.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpof2ak8v0.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow(2 * $i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "56",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmprec3bouf.php:17\nStack trace:\n#0 /tmp/tmprec3bouf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmprec3bouf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp89ikp9qp.php:17\nStack trace:\n#0 /tmp/tmp89ikp9qp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp89ikp9qp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp30htqjq9.php:17\nStack trace:\n#0 /tmp/tmp30htqjq9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp30htqjq9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp89ikp9qp.php:17\nStack trace:\n#0 /tmp/tmp89ikp9qp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp89ikp9qp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyl_l6gqf.php:17\nStack trace:\n#0 /tmp/tmpyl_l6gqf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpyl_l6gqf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpdvbd5vmo.php:17\nStack trace:\n#0 /tmp/tmpdvbd5vmo.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpdvbd5vmo.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpf2mb64sl.php:17\nStack trace:\n#0 /tmp/tmpf2mb64sl.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpf2mb64sl.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i < $n; $i++) {\n        $sum += pow(2 * $i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "120\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpdv9e63b3.php:17\nStack trace:\n#0 /tmp/tmpdv9e63b3.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpdv9e63b3.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbzqg79ml.php:17\nStack trace:\n#0 /tmp/tmpbzqg79ml.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpbzqg79ml.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpnkbd2_rw.php:17\nStack trace:\n#0 /tmp/tmpnkbd2_rw.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpnkbd2_rw.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp89ikp9qp.php:17\nStack trace:\n#0 /tmp/tmp89ikp9qp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp89ikp9qp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow(2*$i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "120",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1;$i<=$n;$i++) {\n        $sum += pow(2*$i,2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "220",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmprec3bouf.php:17\nStack trace:\n#0 /tmp/tmprec3bouf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmprec3bouf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i < $n; $i++) {\n        $sum += pow(2 * $i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "120\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpdv9e63b3.php:17\nStack trace:\n#0 /tmp/tmpdv9e63b3.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpdv9e63b3.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "385\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpkdcbtysa.php:17\nStack trace:\n#0 /tmp/tmpkdcbtysa.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpkdcbtysa.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjncsjihv.php:16\nStack trace:\n#0 /tmp/tmpjncsjihv.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpjncsjihv.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp89ikp9qp.php:17\nStack trace:\n#0 /tmp/tmp89ikp9qp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp89ikp9qp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps_jg8tw9.php:16\nStack trace:\n#0 /tmp/tmps_jg8tw9.php(21): test()\n#1 {main}\n  thrown in /tmp/tmps_jg8tw9.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 2; $i <= $n; $i += 2) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpc93y9410.php:17\nStack trace:\n#0 /tmp/tmpc93y9410.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpc93y9410.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += ($i * $i);\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpv72ipq62.php:16\nStack trace:\n#0 /tmp/tmpv72ipq62.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpv72ipq62.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow(2*$i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "120",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow(2*$i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "56",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\n$n = 4;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpr4_kaqjk.php:18\nStack trace:\n#0 /tmp/tmpr4_kaqjk.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpr4_kaqjk.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6g505ky8.php:17\nStack trace:\n#0 /tmp/tmp6g505ky8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6g505ky8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow(2*$i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "220",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp89ikp9qp.php:17\nStack trace:\n#0 /tmp/tmp89ikp9qp.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp89ikp9qp.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmprec3bouf.php:17\nStack trace:\n#0 /tmp/tmprec3bouf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmprec3bouf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2n_gcrp7.php:17\nStack trace:\n#0 /tmp/tmp2n_gcrp7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2n_gcrp7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxysrawco.php:17\nStack trace:\n#0 /tmp/tmpxysrawco.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxysrawco.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510438,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjncsjihv.php:16\nStack trace:\n#0 /tmp/tmpjncsjihv.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpjncsjihv.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        if($i % 2 == 0) {\n            $sum += pow($i, 2);\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp55ou6wkx.php:19\nStack trace:\n#0 /tmp/tmp55ou6wkx.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp55ou6wkx.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum += pow(2 * $i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "220",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123550,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplwsrgyf2.php:17\nStack trace:\n#0 /tmp/tmplwsrgyf2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmplwsrgyf2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1;$i<=$n;$i++) {\n        $sum += ($i*$i);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpfxao6f_t.php:17\nStack trace:\n#0 /tmp/tmpfxao6f_t.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpfxao6f_t.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i < $n; $i++) {\n        $sum += pow(2 * $i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123551,
      "stdout": "120\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptxlqg2w3.php:17\nStack trace:\n#0 /tmp/tmptxlqg2w3.php(22): test()\n#1 {main}\n  thrown in /tmp/tmptxlqg2w3.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    }
  ]
}